import { defineField, defineType } from "sanity";

export const rfqSubmission = defineType({
  name: "rfqSubmission",
  title: "RFQ submission",
  type: "document",
  fields: [
    defineField({ name: "reference", title: "Reference (RFQ-YYYY-XXXXX)", type: "string" }),
    defineField({ name: "submittedAt", title: "Submitted at", type: "datetime" }),
    defineField({
      name: "source",
      title: "Source",
      type: "string",
      description: "Where the lead came from — 'estimator' for the Solar Rooftop Estimator, blank for the plain quote form.",
    }),
    defineField({
      name: "estimate",
      title: "Solar estimate",
      type: "object",
      description: "Captured from the Solar Rooftop Estimator when the lead started there.",
      options: { collapsible: true, collapsed: false },
      fields: [
        defineField({ name: "segment", title: "Segment", type: "string" }),
        defineField({ name: "phase", title: "Phase", type: "string" }),
        defineField({ name: "monthlyBillThb", title: "Monthly bill (฿)", type: "number" }),
        defineField({ name: "dayUsageFraction", title: "Daytime usage fraction", type: "number" }),
        defineField({ name: "roofAreaSqm", title: "Roof area (m²)", type: "number" }),
        defineField({ name: "recommendedKwp", title: "Recommended size (kWp)", type: "number" }),
        defineField({ name: "packageId", title: "Package ID", type: "string" }),
        defineField({ name: "priceThb", title: "Package price (฿)", type: "number" }),
        defineField({ name: "monthlySavingsThb", title: "Monthly savings (฿)", type: "number" }),
        defineField({ name: "annualSavingsThb", title: "Annual savings (฿)", type: "number" }),
        defineField({ name: "paybackYears", title: "Payback (years)", type: "number" }),
        defineField({ name: "lifetimeSavingsThb", title: "25-yr savings (฿)", type: "number" }),
        defineField({ name: "annualCo2SavedKg", title: "CO₂ saved / yr (kg)", type: "number" }),
        defineField({ name: "verdict", title: "Verdict", type: "string" }),
      ],
    }),
    defineField({ name: "projectType", title: "Project type", type: "string" }),
    defineField({ name: "projectSize", title: "Project size", type: "string" }),
    defineField({
      name: "productsOfInterest",
      title: "Products of interest",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({ name: "timeline", title: "Timeline", type: "string" }),
    defineField({ name: "name", title: "Name", type: "string" }),
    defineField({ name: "company", title: "Company", type: "string" }),
    defineField({ name: "email", title: "Email", type: "string" }),
    defineField({ name: "phone", title: "Phone", type: "string" }),
    defineField({ name: "role", title: "Role", type: "string" }),
    defineField({ name: "notes", title: "Notes", type: "text" }),
    defineField({ name: "attachment", title: "Attachment", type: "file" }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: { list: ["new", "contacted", "qualified", "won", "lost"] },
      initialValue: "new",
    }),
  ],
  preview: {
    select: { title: "reference", subtitle: "company", description: "email" },
  },
});
